"""Type stubs for the noob_core rust extension module."""

from typing import TypeAlias

NativeItem: TypeAlias = str | tuple[str, str]
NativeEpoch: TypeAlias = list[tuple[str, int]]
NativeEpochIn: TypeAlias = tuple[tuple[str, int], ...] | list[tuple[str, int]]
NativeNodes: TypeAlias = list[tuple[str, bool]]
NativeEdges: TypeAlias = list[tuple[str, str, str, bool]]
NativeNodeInfo: TypeAlias = tuple[
    NativeItem, int, list[NativeItem], list[NativeItem], list[NativeItem], list[NativeItem]
]

class SchedulerError(Exception): ...
class AlreadyDoneError(SchedulerError): ...
class NotAddedError(SchedulerError): ...
class EpochExistsError(SchedulerError): ...
class EpochCompletedError(SchedulerError): ...

class CoreTopoSorter:
    def __init__(
        self, nodes: NativeNodes | None = None, edges: NativeEdges | None = None
    ) -> None: ...
    def add(
        self, node: NativeItem, predecessors: list[NativeItem], required: bool = True
    ) -> None: ...
    def get_ready(self, node_id: str | None = None) -> list[NativeItem]: ...
    def is_active(self) -> bool: ...
    def done(self, nodes: list[NativeItem]) -> None: ...
    def mark_ready(self, nodes: list[NativeItem]) -> None: ...
    def mark_out(self, nodes: list[NativeItem]) -> None: ...
    def mark_expired(self, nodes: list[NativeItem], unlock_optionals: bool = True) -> None: ...
    def resurrect(self, nodes: list[NativeItem]) -> None: ...
    def find_cycle(self) -> list[NativeItem] | None: ...
    def ready_nodes(self) -> list[NativeItem]: ...
    def out_nodes(self) -> list[NativeItem]: ...
    def done_nodes(self) -> list[NativeItem]: ...
    def ran_nodes(self) -> list[NativeItem]: ...
    def disabled_nodes(self) -> list[NativeItem]: ...
    def counters(self) -> tuple[int, int]: ...
    def node_info(self) -> list[NativeNodeInfo]: ...
    def signals(self) -> list[tuple[str, list[NativeItem]]]: ...
    def shares_state_with(self, other: CoreTopoSorter) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __deepcopy__(self, memo: object) -> CoreTopoSorter: ...
    def __copy__(self) -> CoreTopoSorter: ...

class CoreScheduler:
    def __init__(
        self,
        nodes: NativeNodes,
        edges: NativeEdges,
        source_nodes: list[str] | None = None,
    ) -> None: ...
    def source_nodes(self) -> list[str]: ...
    def sorter(self, epoch: NativeEpochIn) -> CoreTopoSorter: ...
    def add_epoch(self, epoch: NativeEpochIn | None = None) -> NativeEpoch: ...
    def add_subepoch(self, epoch: NativeEpochIn) -> None: ...
    def ensure(self, epoch: NativeEpochIn) -> None: ...
    def contains_epoch(self, epoch: NativeEpochIn) -> bool: ...
    def epoch_keys(self) -> list[NativeEpoch]: ...
    def latest_epoch(self) -> NativeEpoch: ...
    def epoch_log(self) -> list[int]: ...
    def subepoch_map(self) -> list[tuple[NativeEpoch, list[NativeEpoch]]]: ...
    def is_active(self, epoch: NativeEpochIn | None = None) -> bool: ...
    def get_ready(
        self, epoch: NativeEpochIn | None = None, node_id: str | None = None
    ) -> tuple[list[tuple[NativeEpoch, NativeItem]], list[tuple[NativeEpoch, NativeItem]]]: ...
    def node_is_ready(self, node: str, epoch: NativeEpochIn | None = None) -> bool: ...
    def node_is_done(self, node: str, epoch: NativeEpochIn) -> bool: ...
    def sources_finished(self, epoch: NativeEpochIn | None = None) -> bool: ...
    def done(
        self,
        epoch: NativeEpochIn,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
    ) -> bool: ...
    def expire(
        self,
        epoch: NativeEpochIn,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
        unlock_optionals: bool = True,
    ) -> bool: ...
    def epoch_completed(self, epoch: NativeEpochIn) -> bool: ...
    def end_epoch(self, epoch: NativeEpochIn | None = None) -> NativeEpoch | None: ...
    def enable_node(self, node_id: str) -> None: ...
    def disable_node(self, node_id: str) -> None: ...
    def clear(self) -> None: ...
    def has_cycle(self) -> bool: ...
    def generations(self) -> list[list[NativeItem]]: ...
    def upstream_nodes(self, node: str) -> list[str]: ...
    def __deepcopy__(self, memo: object) -> CoreScheduler: ...
    def __copy__(self) -> CoreScheduler: ...
