"""Type stubs for the noob_core rust extension module."""

from collections.abc import Sequence
from logging import Logger
from typing import Any, TypeAlias

# noob_core constructs real noob objects at the boundary
# (noob.types.Epoch / NodeSignal, noob.event.MetaEvent dicts) -
# typed as Any here so the stub does not depend on noob
Epoch: TypeAlias = Any
MetaEvent: TypeAlias = Any
GraphItem: TypeAlias = Any
NodeInfo: TypeAlias = Any
Edge: TypeAlias = Any
NodeSpecification: TypeAlias = Any
Event: TypeAlias = Any

class SchedulerError(Exception): ...
class AlreadyDoneError(SchedulerError): ...
class NotAddedError(SchedulerError): ...
class EpochExistsError(SchedulerError): ...
class EpochCompletedError(SchedulerError): ...

class CoreTopoSorter:
    def __init__(
        self,
        nodes: dict[str, NodeSpecification] | None = None,
        edges: list[Edge] | None = None,
    ) -> None: ...
    def add(
        self, node: GraphItem, predecessors: list[GraphItem], required: bool = True
    ) -> None: ...
    def get_ready(self, node_id: str | None = None) -> tuple[GraphItem, ...]: ...
    def is_active(self) -> bool: ...
    def done(self, nodes: list[GraphItem]) -> None: ...
    def mark_ready(self, nodes: list[GraphItem]) -> None: ...
    def mark_out(self, nodes: list[GraphItem]) -> None: ...
    def mark_expired(
        self, nodes: list[GraphItem], unlock_optionals: bool = True, cascade: bool = False
    ) -> tuple[GraphItem, ...]: ...
    def resurrect(self, nodes: list[GraphItem]) -> None: ...
    def find_cycle(self) -> list[GraphItem] | None: ...
    def ready_nodes(self) -> set[GraphItem]: ...
    def out_nodes(self) -> set[GraphItem]: ...
    def done_nodes(self) -> set[GraphItem]: ...
    def ran_nodes(self) -> set[GraphItem]: ...
    def disabled_nodes(self) -> set[GraphItem]: ...
    def counters(self) -> tuple[int, int]: ...
    def node_info(self) -> dict[GraphItem, NodeInfo]: ...
    def signals(self) -> dict[str, set[GraphItem]]: ...
    def shares_state_with(self, other: CoreTopoSorter) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __deepcopy__(self, memo: object) -> CoreTopoSorter: ...
    def __copy__(self) -> CoreTopoSorter: ...

class CoreScheduler:
    def __init__(
        self,
        nodes: dict[str, NodeSpecification],
        edges: list[Edge],
        source_nodes: list[str] | None = None,
        logger: Logger | None = None,
    ) -> None: ...
    def source_nodes(self) -> list[str]: ...
    def graph_signals(self) -> set[tuple[str, str]]: ...
    def getitem(self, epoch: Epoch | int) -> CoreTopoSorter: ...
    def sorter(self, epoch: Epoch) -> CoreTopoSorter: ...
    def add_epoch(self, epoch: Epoch | int | None = None) -> Epoch: ...
    def add_subepoch(self, epoch: Epoch) -> Epoch: ...
    def contains_epoch(self, epoch: Epoch) -> bool: ...
    def epoch_keys(self) -> list[Epoch]: ...
    def epoch_log(self) -> list[int]: ...
    def subepochs(self) -> dict[Epoch, set[Epoch]]: ...
    def is_active(self, epoch: Epoch | None = None) -> bool: ...
    def get_ready(
        self, epoch: Epoch | None = None, node_id: str | None = None
    ) -> list[MetaEvent]: ...
    def node_is_ready(self, node: str, epoch: Epoch | None = None) -> bool: ...
    def node_is_done(self, node: str, epoch: Epoch) -> bool: ...
    def sources_finished(self, epoch: Epoch | None = None) -> bool: ...
    def update(self, events: Sequence[Event]) -> list[Event]: ...
    def done(
        self,
        epoch: Epoch,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
    ) -> MetaEvent | None: ...
    def expire(
        self,
        epoch: Epoch,
        node_id: str,
        signal: str | None = None,
        with_signals: bool = True,
        unlock_optionals: bool = True,
        cascade: bool = True,
    ) -> MetaEvent | None: ...
    def queue_epoch(self, epoch: Epoch | int) -> Epoch: ...
    def queue_epochs(self, n: int) -> list[Epoch]: ...
    def set_freerun(self, enabled: bool) -> None: ...
    def next_events(self, node_id: str | None = None) -> list[MetaEvent]: ...
    def epoch_completed(self, epoch: Epoch) -> bool: ...
    def end_epoch(self, epoch: Epoch | int | None = None) -> MetaEvent | None: ...
    def enable_node(self, node_id: str) -> None: ...
    def disable_node(self, node_id: str) -> None: ...
    def clear(self) -> None: ...
    def has_cycle(self) -> bool: ...
    def generations(self) -> list[tuple[GraphItem, ...]]: ...
    def asset_generations(self) -> dict[str, list[tuple[str, ...]]]: ...
    def upstream_nodes(self, node: str) -> set[str]: ...
    def __deepcopy__(self, memo: object) -> CoreScheduler: ...
    def __copy__(self) -> CoreScheduler: ...
